services:
  clustering:
    hostname: clustering
    image: davidedomini99/experiments-electricity-map-data:1.0.0
    volumes:
      - davide.domini-volume:/data
    environment:
      DATA_OWNER: 1000:1000

volumes:
  davide.domini-volume:
    external: true